version: "3.9"
services:
  db:
    image: postgres:13.5
    restart: always
    environment:
      POSTGRES_PASSWORD: diego00 
    
  app:
    depends_on:
      - db
    image: diegob/app01:1
    restart: always
    ports:
      - "9009:9009"
    environment:
      HOST: db
      LPORT: "9009"
